<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>Tsukikage</AssemblyName>
    <NoWin32Manifest>true</NoWin32Manifest>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="sharpconfig" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Tsukikage.exe.manifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Tsukikage.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="update-helper.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
